### ISSUE TITLE
Questions about evaluation

### ISSUE THREAD

**Issue by Wuziyi616** [google/storybench#6]
Hi, as mentioned in the paper, automatic metrics are not very useful for measuring the model performance. User study is preferred instead. I wonder is it possible to share some videos generated by the baseline Phenaki model (just the zero-shot one is fine)? Otherwise it would be impossible to do user study to compare with our method. Though I understand that it's kinda hard to release assets in Google projects..

**Comment by e-bug** [comment]
Unfortunately, the Phenaki generated videos are no longer available.

Also, I would recommend more recent models as baselines, as we used a very small Phenaki model.

**Comment by Wuziyi616** [comment]
Very true. Though to be very honest the task of story generation hasn't attracted many attention thus it's hard to setup baselines... Most relevant works generate video clips with cutscenes in between instead of continuous segments.
